## list length

In [1]:
### Naver Developers - Open API
import urllib
# Open API 사용 요청
client_id = 'PG3kwbDlhgk80hJqt_Ob'
client_secret = 'fbMT9Q0JGb'


def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

def search_title(title):
    encText = urllib.parse.quote(title)
    url = 'https://openapi.naver.com/v1/search/movie.json?display=100&query=' + encText
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        d = json.loads(response_body.decode('utf-8'))
        if (len(d['items']) > 0):
            return d['items']
        else:
            return None

    else:
        print("Error Code:" + rescode)

In [2]:
import requests

In [214]:
d = search_title('레드후드')

In [224]:
d

[{'title': '리틀 <b>레드</b> 리딩 <b>후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=205514',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/2055/205514_P01_140836.jpg',
  'subtitle': 'Little Red Riding Hood',
  'pubDate': '2021',
  'director': '보이코 카네브|',
  'actor': '',
  'userRating': '0.00'},
 {'title': '<b>레드</b> 라이딩 <b>후드</b> 리덱스',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=164883',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/1648/164883_P01_175358.jpg',
  'subtitle': 'Red Riding Hood Redux',
  'pubDate': '2017',
  'director': '다니엘 제젤|',
  'actor': '',
  'userRating': '0.00'},
 {'title': '<b>레드 후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=141221',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/1412/141221_P01_113531.jpg',
  'subtitle': 'Little Red Riding Hood',
  'pubDate': '2016',
  'director': '르네 페르즈|',
  'actor': '로버트 앰슬러|니콜 스탁|로버트 S. 딕슨|',
  'userRating': '0.00'},
 {'title': '<b>레드</b> 라이딩 <b>후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=76451',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/0764/76451_P04_144854.jpg',
  'subtitle': 'Red Riding Hood',
  'pubDate': '2011',
  'director': '캐서린 하드윅|',
  'actor': '아만다 사이프리드|게리 올드만|',
  'userRating': '7.02'},
 {'title': '배트맨 - 언더 더 <b>레드 후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=77550',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/0775/77550_P03_163630.jpg',
  'subtitle': 'Batman: Under The Red Hood',
  'pubDate': '2010',
  'director': '브랜던 비에티|',
  'actor': '브루스 그린우드|젠슨 애클스|',
  'userRating': '8.91'},
 {'title': '페로즈: 더 와일드 <b>레드</b> 라이딩 <b>후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=84784',
  'image': '',
  'subtitle': 'Ferozz: The Wild Red Riding Hood',
  'pubDate': '2010',
  'director': '호르헤 몰리나|',
  'actor': '데이아나 레그라|로베르토 페르도모|',
  'userRating': '0.00'},
 {'title': '빨간 모자',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=81791',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/0817/81791_P01_113354.jpg',
  'subtitle': 'Little Red Riding Hood',
  'pubDate': '1997',
  'director': '데이빗 캐플란|',
  'actor': '크리스티나 리치|티무어 부타센코브|',
  'userRating': '0.00'},
 {'title': '더 메리드 라이프 오브 리틀 <b>레드</b> 라이딩 <b>후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=125876',
  'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/1258/125876_P01_170203.jpg',
  'subtitle': 'The Married Life Of Little Red Riding Hood(Farce)',
  'pubDate': '1973',
  'director': '즐라코 부렉|',
  'actor': '',
  'userRating': '0.00'},
 {'title': '<b>레드</b> 핫 라이딩 <b>후드</b>',
  'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=62786',
  'image': '',
  'subtitle': 'Red Hot Riding Hood',
  'pubDate': '1943',
  'director': '텍스 에이버리|',
  'actor': '도스 버틀러|준 포레이|',
  'userRating': '0.00'}]

In [221]:
for n in (range(len(d))):
    if d
    a = d[n]['director'] == '르네 페르즈|'

False
False
True
False
False
False
False
False
False

In [229]:
for n in (range(len(d))):
    if d[i]['director'][:-1] == data[data['title'] == f'{keyword}']['directors'].values:
        break
    movie = d[i]

In [230]:
movie

{'title': '리틀 <b>레드</b> 리딩 <b>후드</b>',
 'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=205514',
 'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/2055/205514_P01_140836.jpg',
 'subtitle': 'Little Red Riding Hood',
 'pubDate': '2021',
 'director': '보이코 카네브|',
 'actor': '',
 'userRating': '0.00'}

In [210]:
d[0]['director']

'보이코 카네브|'

In [3]:
import pandas as pd
data = pd.read_csv("data_star_기대.csv")
data.head(10)

,Unnamed: 0,title,directors,actors,plots,genre,runtime,keywords,등급,국적,screenCnt,audiAcc,salesAcc,개봉일,제작비,네이버_기대지수,star_buzz
0,0,물괴,허종호,"김명민, 김인권, 혜리, 최우식, 이경영, 박희순, 박성웅, 이도경, 김중희, 이규...",“인왕산에 흉악한 짐승이 나타나 사람을 해쳤다 하옵니다.그것을 두고 듣지도 보지도 ...,액션,105.0,"조선시대,전염병,괴물,시대극/사극,사투",15세이상관람가,한국,1183.0,723414.0,6.104165e+09,2018-09-12,1.250000e+10,1274.0,1629
1,1,싱글라이더,이주영,"이병헌, 공효진, 안소희, 잭 캠벨, 양유진, 애니카 화이틀리, 케이 에크룬드, 백...",그가 사라졌다그에게서 모든 것이 사라졌다증권회사의 지점장 강재훈(이병헌). 안정된 ...,드라마,97.0,"기러기아빠,호주,오스트레일리아,반전,반전영화,동물",15세이상관람가,한국,576.0,351276.0,2.685519e+09,2017-02-22,4.500000e+09,3838.0,581
2,2,허스토리,민규동,"김희애, 김해숙, 예수정, 문숙, 이용녀, 김선영, 김준한, 이유영, 이지하, 이용...","이겨야죠! 이겨야 할매들 분이 안풀리겠습니까? 1992~1998 6년의 기간, 2...",드라마,121.0,"종군위안부,위안부,일본군위안부피해자,실화바탕,재판,관부재판,정신대,정신대할머니,법정...",12세이상관람가,한국,696.0,336822.0,2.521026e+09,2018-06-27,2.500000e+09,494.0,943
3,3,풀잎들,홍상수,"김민희, 정진영, 기주봉, 서영화, 김새벽, 안재홍, 공민정, 안선영, 신석호, 김...",커피집이 있을 것 같지 않은 골목 안으로 커피집이 있고 사람들이 커피집 안 여기저기...,드라마,66.0,"삶과죽음,타인의 삶,언행,부산국제영화제,베를린영화제,삶의굴레,삶의순환,삶의의미",15세이상관람가,한국,54.0,7443.0,6.032025e+07,2018-10-25,1.000000e+08,162.0,111
4,4,영주,차성덕,"김향기, 김호정, 유재명, 탕준상, 장혜진, 김용준, 강동윤, 박옥출, 현봉식, 전...",나쁘고 좋은 사람들을 만났다.교통사고로 부모를 잃고 졸지에 가장이 된 영주는 자신의...,드라마,101.0,"부산국제영화제,부모님의죽음,장편데뷔작,복수극",12세이상관람가,한국,106.0,24823.0,1.927298e+08,2018-11-22,2.200000e+08,800.0,335
5,5,여배우는 오늘도,문소리,"문소리, 강숙, 김경선, 원동연, 김래원, 이정익, 윤영균, 성병숙, 윤초희, 오민...","배우 문소리는 오늘도 며느리, 딸, 엄마, 아내 역할로 만취 상태다. 정작 맡고 싶...",드라마,71.0,"며느리,딸,엄마,아내,여배우,연기,감독,성장,자력갱생",15세이상관람가,한국,46.0,16646.0,1.370103e+08,2017-09-14,1.000000e+08,1128.0,77
6,6,다영씨,고봉수,"신민재, 이호정, 강하람, 박원진, 백승환, 조준희, 김충길, 김정기, 김용진, 손...",퀵서비스 기사 민재는 매일 삼진물산에 도착할 택배를 기다린다. 그곳에서 일하는 다영...,드라마,61.0,"짝사랑,흑백영화,무성영화,애환,퀵서비스",12세이상관람가,한국,19.0,797.0,5.206600e+06,2018-12-06,1.000000e+06,69.0,61
7,7,상류사회,변혁,"박해일, 수애, 윤제문, 라미란, 이진욱, 김규선, 한주영, 김해곤, 남문철, 장소...","“왜, 재벌들만 겁 없이 사는 줄 알았어?”학생들에게 인기와 존경을 동시에 받는 경...",드라마,120.0,"욕망,상류층,대학교수,야망,국회의원선거,암거래,상류사회,정치권력,권력쟁취,불륜",청소년관람불가,한국,867.0,768442.0,6.313416e+09,2018-08-29,8.000000e+09,364.0,752
8,8,어른도감,김인선,"엄태구, 이재인, 서정연, 김희창, 황정민, 박성연, 송별, 이영숙, 장혜진, 공상...",“도대체 진짜 어른 맞아요?”열 네 살 경언은 아버지 장례식장에서 생면부지의 삼촌 ...,코미디,92.0,"사기극,가족,위로,부녀관계,어른동화,기분전환",12세이상관람가,한국,58.0,7056.0,5.353970e+07,2018-08-23,7.000000e+07,95.0,198
9,9,궁합,홍창표,"심은경, 이승기, 김상경, 연우진, 강민혁, 최우식, 조복래, 박선영, 이윤건, 김...",“세상의 모든 인연에는 궁합이 있다!” 관상은 잘 보았소? 이제 궁합을 봐드리지!극...,코미디,110.0,"인연,궁합,조선시대,부마 간택,혼사,사주팔자",12세이상관람가,한국,966.0,1340117.0,1.047888e+10,2018-02-28,6.300000e+09,5828.0,809

In [5]:
direct = data['directors']

In [6]:
df = data["title"]
df

0                물괴
1             싱글라이더
2              허스토리
3               풀잎들
4                영주
           ...
570            히말라야
571             허삼관
572    해적: 바다로 간 산적
573             숫호구
574            1987
Name: title, Length: 575, dtype: object

각 영화의 고유 코드 가져오기

In [7]:
code_lst = []
title_lst = []

for i in df.index[:]: #4272
    keyword = df[i]
    m = search_title(keyword)
                
    try:
        for n in (range(len(m))):
            if m[n]['director'][:-1] == data[data['title'] == f'{keyword}']['directors'].values:
                break
        link = m[n]['link']
        spl = str(link).split("=")
        it = spl[1]
        code_lst.append(it)
        
        title1 = m[n]['title']
        #title = title1_tag[0]
        title_lst.append(title1)
    except:
        code_lst.append('nan')
        title_lst.append(keyword)

In [8]:
while 'nan' in code_lst:
    code_lst.remove('nan')

In [9]:
len(code_lst)

575

In [10]:
title_lst

['<b>물괴</b>',
 '<b>싱글라이더</b>',
 '<b>허스토리</b>',
 '<b>풀잎들</b>',
 '<b>영주</b>',
 '<b>여배우는 오늘도</b>',
 '<b>다영씨</b>',
 '<b>상류사회</b>',
 '<b>어른도감</b>',
 '<b>궁합</b>',
 '<b>리틀 포레스트</b>',
 '<b>튼튼이의 모험</b>',
 '<b>목격자</b>',
 '<b>더 테이블</b>',
 '<b>마녀</b>(魔女) Part2. The Other One',
 '<b>당신의 부탁</b>',
 '<b>인랑</b>',
 '<b>소성리</b>',
 '<b>덕구</b>',
 '<b>골든슬럼버</b>',
 '<b>불한당: 나쁜 놈들의 세상</b>',
 '<b>수성못</b>',
 '<b>버닝</b>',
 '<b>왓칭</b>',
 '<b>7호실</b>',
 '<b>그것만이 내 세상</b>',
 '<b>박열</b>',
 '<b>재심</b>',
 '<b>범죄도시</b>',
 '<b>그날, 바다</b>',
 '<b>델타 보이즈</b>',
 '<b>반드시 잡는다</b>',
 '<b>완벽한 타인</b>',
 '<b>환절기</b>',
 '<b>독전</b>',
 '<b>폴란드로 간 아이들</b>',
 '<b>봉이 김선달</b>',
 '<b>영하의 바람</b>',
 '<b>용순</b>',
 '<b>사라진 밤</b>',
 '<b>강변호텔</b>',
 '<b>오목소녀</b>',
 '<b>창궐</b>',
 '<b>극한직업</b>',
 '<b>희생부활자</b>',
 '<b>이웃집 스타</b>',
 '<b>82년생 김지영</b>',
 '<b>여중생A</b>',
 '<b>칠곡 가시나들</b>',
 '<b>너의 결혼식</b>',
 '<b>유령선</b>',
 '<b>뷰티풀 데이즈</b>',
 '<b>호랑이보다 무서운 겨울손님</b>',
 '<b>윤희에게</b>',
 '<b>엑시트</b>',
 '<b>데자뷰</b>',
 '<b>조선명탐정: 흡혈괴마의 비밀</b>',
 '<b>레슬러</b>',
 '<b>찬실이는 복도 많지</b>',
 '<b>하루</b>',
 '<b>악녀</b>',
 '<b>정의심판</b>',
 '<b>챔피언</b>',
 '<b>기억의 밤</b>',
 '<b>게이트</b>',
 '<b>지푸라기라도 잡고 싶은 짐승들</b>',
 '<b>롱 리브 더 킹: 목포 영웅</b>',
 '<b>보통사람</b>',
 '<b>아티스트: 다시 태어나다</b>',
 '<b>팡파레</b>',
 '<b>이태원</b>',
 '<b>지금 만나러 갑니다</b>',
 '<b>내안의 그놈</b>',
 '<b>무현, 두 도시 이야기</b>',
 '<b>분장</b>',
 '<b>뷰티플 마인드</b>',
 '<b>0.0MHz</b>',
 '<b>오늘도 평화로운</b>',
 '<b>어른이 되면</b>',
 '<b>아직 사랑하고 있습니까?</b>',
 '<b>수상한 이웃</b>',
 '<b>변신</b>',
 '<b>B급 며느리</b>',
 '<b>7년의 밤</b>',
 '<b>소공녀</b>',
 '<b>프리즌</b>',
 '<b>원더풀 고스트</b>',
 '<b>공작</b>',
 '<b>국가부도의 날</b>',
 '<b>말모이</b>',
 '<b>석조저택 살인사건</b>',
 '<b>재꽃</b>',
 '<b>시간위의 집</b>',
 '<b>커튼콜</b>',
 '<b>사냥</b>',
 '<b>럭키</b>',
 '<b>청춘 합창단 - 또 하나의 꿈</b>',
 '<b>특별수사: 사형수의 편지</b>',
 '<b>딜쿠샤</b>',
 '<b>우리</b>집',
 '<b>아수라</b>',
 '<b>여수 밤바다</b>',
 '<b>히야</b>',
 '<b>귀향, 끝나지 않은 이야기</b>',
 '<b>저수지 게임</b>',
 '<b>형</b>',
 '<b>날, 보러와요</b>',
 '<b>마리안느와 마가렛</b>',
 '<b>원스텝</b>',
 '<b>군함도</b>',
 '<b>밀정</b>',
 '<b>나를 잊지 말아요</b>',
 '<b>최악의 하루</b>',
 '<b>조선마술사</b>',
 '<b>그날의 분위기</b>',
 '<b>돌연변이</b>',
 '<b>비치온더비치</b>',
 '<b>퇴마: 무녀굴</b>',
 '<b>어떤살인</b>',
 '<b>굿바이 싱글</b>',
 '<b>아기와 나</b>',
 '<b>콜리션</b>',
 '<b>국가대표2</b>',
 '<b>미션스쿨</b>',
 '<b>계춘할망</b>',
 '<b>시간이탈자</b>',
 '<b>판도라</b>',
 '<b>리얼</b>',
 '<b>루시드 드림</b>',
 '<b>죽여주는 여자</b>',
 '<b>마돈나</b>',
 '<b>나의 절친 악당들</b>',
 '<b>글로리데이</b>',
 '<b>인천상륙작전</b>',
 '<b>퍼스트 스텝</b>',
 '<b>남한산성</b>',
 '<b>국정교과서 516일: 끝나지 않은 역사전쟁</b>',
 '<b>미씽: 사라진 여자</b>',
 '<b>마스터</b>',
 '<b>아이 캔 스피크</b>',
 '<b>살인자의 기억법</b>',
 '<b>당신, 거기 있어줄래요</b>',
 '<b>깡치</b>',
 '<b>버블 패밀리</b>',
 '<b>혼숨</b>',
 '<b>스플릿</b>',
 '<b>야근 대신 뜨개질</b>',
 '<b>산상수훈</b>',
 '<b>나는 증인이다</b>',
 '<b>연애담</b>',
 '<b>7년-그들이 없는 언론</b>',
 '<b>청년경찰</b>',
 '<b>공범자들</b>',
 '<b>흔들리는 물결</b>',
 '<b>비밀은 없다</b>',
 '<b>걷기왕</b>',
 '<b>택시운전사</b>',
 '<b>나홀로 휴가</b>',
 '<b>조작된 도시</b>',
 '<b>기적</b>',
 '<b>계절과 계절 사이</b>',
 '<b>동백</b>',
 '<b>디바</b>',
 '<b>니나 내나</b>',
 '<b>퍼펙트맨</b>',
 '<b>봉오동 전투</b>',
 '<b>싱크홀</b>',
 '<b>국제수사</b>',
 '<b>다만 악에서 구하소서</b> 파이널컷',
 '<b>강철비2: 정상회담</b>',
 '<b>로마서 8:37</b>',
 '<b>죽지않는 인간들의 밤</b>',
 '<b>판소리 복서</b>',
 '<b>미션 파서블</b>',
 '<b>오! 문희</b>',
 '수양과 <b>백두산</b>',
 '<b>어게인</b>',
 '<b>좀비크러쉬: 헤이리</b>',
 '<b>모가디슈</b>',
 '<b>서복</b>',
 '<b>이 안에 외계인이 있다</b>',
 '<b>나랏말싸미</b>',
 '<b>난폭한 기록</b>',
 '<b>부러진 화살</b>',
 '<b>럭키 몬스터</b>',
 '<b>인트로덕션</b>',
 '<b>인질</b>',
 '<b>왕십리 김종분</b>',
 '<b>나쁜 녀석들: 더 무비</b>',
 '<b>유체이탈자</b>',
 '<b>벌새</b>',
 '<b>더 박스</b>',
 '광대: <b>소리꾼</b>',
 '<b>히트맨</b>',
 '<b>구직자들</b>',
 '<b>세트플레이</b>',
 '<b>결백</b>',
 '<b>그물</b>',
 '<b>사라진 시간</b>',
 '<b>해적: 도깨비 깃발</b>',
 '<b>유리정원</b>',
 '<b>나는보리</b>',
 '<b>신의 한 수: 귀수편</b>',
 '<b>기도하는 남자</b>',
 '<b>발신제한</b>',
 '<b>1급기밀</b>',
 '<b>운동회</b>',
 '<b>나의 특별한 형제</b>',
 '<b>인천스텔라</b>',
 '<b>트로트는 인생이다</b>',
 '<b>아내를 죽였다</b>',
 '<b>반도</b>',
 '<b>빛과 철</b>',
 '<b>런 보이 런</b>',
 '<b>선샤인 패밀리</b>',
 '<b>자산어보</b>',
 '<b>이웃사촌</b>',
 '<b>사라센의 칼</b>',
 '<b>삼진그룹 영어토익반</b>',
 '<b>우리집</b>',
 '<b>태백권</b>',
 '<b>내가 죽던 날</b>',
 '<b>타다: 대한민국 스타트업의 초상</b>',
 '<b>쇠파리</b>',
 '<b>천문: 하늘에 묻는다</b>',
 '<b>담보</b>',
 '<b>내일의 기억</b>',
 '<b>브이아이피</b>',
 '<b>힘을 내요, 미스터 리</b>',
 '<b>갈까부다</b>',
 '<b>야구소녀</b>',
 '<b>장마</b>',
 '<b>어린 의뢰인</b>',
 '<b>미옥</b>',
 '<b>유열의 음악앨범</b>',
 '<b>원라인</b>',
 '<b>서부전선</b>',
 '<b>염력</b>',
 '<b>돌아와요 부산항애(愛)</b>',
 '<b>가장 보통의 연애</b>',
 '<b>협상</b>',
 '<b>PMC: 더 벙커</b>',
 '<b>부라더</b>',
 '<b>장르만 로맨스</b>',
 '<b>미쓰백</b>',
 '<b>행동하는 양심 김대중</b>',
 '<b>더 킹</b>',
 '<b>침묵</b>',
 '<b>자전차왕 엄복동</b>',
 '<b>성혜의 나라</b>',
 '<b>출국</b>',
 '<b>블랙머니</b>',
 '<b>킹메이커</b>',
 '<b>증인</b>',
 '<b>걸캅스</b>',
 '<b>공조</b>',
 '<b>1919 유관순</b>',
 '<b>폭력의 씨앗</b>',
 '<b>괴물들</b>',
 '<b>호흡</b>',
 '<b>신과함께-죄와 벌</b>',
 '<b>비정규직 특수요원</b>',
 '<b>강철비</b>2: 정상회담',
 '<b>장산범</b>',
 '<b>암전</b>',
 '<b>우상</b>',
 '<b>사자</b>',
 '<b>대립군</b>',
 '<b>헤로니모</b>',
 '<b>안시성</b>',
 '<b>악인전</b>',
 '<b>바람 바람 바람</b>',
 '<b>프리즈너</b>',
 '<b>기생충</b>',
 '<b>미성년</b>',
 '<b>캐논볼</b>',
 '<b>F20</b>',
 '<b>미스터 주: 사라진 VIP</b>',
 '<b>신과함께-인과 연</b>',
 '<b>사바하</b>',
 '<b>탐정: 리턴즈</b>',
 '<b>저승보다 낯선</b>',
 '<b>임금님의 사건수첩</b>',
 '더 <b>보이스</b> 클럽',
 '<b>악질경찰</b>',
 '<b>공수도</b>',
 '<b>노무현입니다</b>',
 '<b>타짜: 원 아이드 잭</b>',
 '<b>대장 김창수</b>',
 '<b>기술자들</b>',
 '<b>아워 미드나잇</b>',
 '<b>랑종</b>',
 '<b>방법: 재차의</b>',
 '<b>액션히어로</b>',
 '<b>돌멩이</b>',
 '<b>기기괴괴 성형수</b>',
 '<b>도굴</b>',
 '<b>비스트</b>',
 '<b>오케이 마담</b>',
 '<b>소리도 없이</b>',
 '<b>시동</b>',
 '<b>아이</b>',
 '<b>더 플랜</b>',
 '<b>작은 빛</b>',
 '<b>특별시민</b>',
 '<b>불량한 가족</b>',
 '<b>살아남은 아이</b>',
 '<b>남산의 부장들</b>',
 '<b>잔칫날</b>',
 '<b>항거:유관순 이야기</b>',
 '<b>도어락</b>',
 '<b>광대들: 풍문조작단</b>',
 '<b>마약왕</b>',
 '<b>생일</b>',
 '<b>클로젯</b>',
 '<b>보안관</b>',
 '<b>스윙키즈</b>',
 '<b>뺑반</b>',
 '<b>기묘한 가족</b>',
 '<b>고양이 집사</b>',
 '<b>메기</b>',
 '<b>해치지않아</b>',
 '<b>나와 봄날의 약속</b>',
 '<b>꾼</b>',
 '<b>어쩌다, 결혼</b>',
 '<b>양자물리학</b>',
 '<b>머니백</b>',
 '<b>치즈인더트랩</b>',
 '<b>진범</b>',
 '<b>메소드</b>',
 '<b>변산</b>',
 '<b>바람의 언덕</b>',
 '<b>돈</b>',
 '<b>저 산 너머</b>',
 '<b>생각의 여름</b>',
 '<b>나의 PS 파트너</b>',
 '<b>돈 크라이 마미</b>',
 '<b>아부의 왕</b>',
 '<b>베를린</b>',
 '<b>5백만불의 사나이</b>',
 '<b>태아 3D</b>',
 '<b>설인</b>',
 '<b>26년</b>',
 '<b>577 프로젝트</b>',
 '<b>두레소리</b>',
 '<b>경복</b>',
 '<b>두 개의 달</b>',
 '<b>나는 공무원이다</b>',
 '<b>미쓰GO</b>',
 '<b>화차</b>',
 '<b>시체가 돌아왔다</b>',
 '<b>동학, 수운 최제우</b>',
 '<b>미스터 고</b>',
 '<b>회초리</b>',
 '<b>회사원</b>',
 '<b>남자사용설명서</b>',
 '<b>남영동1985</b>',
 '<b>점쟁이들</b>',
 '<b>바람과 함께 사라지다</b>',
 '<b>내가 살인범이다</b>',
 '<b>심장이 뛴다</b>',
 '<b>광해, 왕이 된 남자</b>',
 '<b>타워</b>',
 '<b>오싹한 연애</b>',
 '<b>붉은 바캉스 검은 웨딩</b>',
 '<b>퀵</b>',
 '<b>천사의 숨소리</b>',
 '<b>완득이</b>',
 '<b>무산일기</b>',
 '<b>고지전</b>',
 '<b>영건 탐정사무소</b>',
 '<b>러브픽션</b>',
 '<b>최종병기 활</b>',
 '<b>로맨틱 헤븐</b>',
 '<b>사물의 비밀</b>',
 '<b>미운 오리 새끼</b>',
 '<b>심장이 뛰네</b>',
 '<b>은교</b>',
 '<b>공모자들</b>',
 '<b>내 아내의 모든 것</b>',
 '<b>7번방의 선물</b>',
 '<b>방독피</b>',
 '<b>반창꼬</b>',
 '<b>피에타</b>',
 '<b>이웃사람</b>',
 '아주 <b>무서운 이야기</b> - 어둠의 까마귀',
 '<b>연가시</b>',
 '<b>우리 이웃의 범죄</b>',
 '<b>1999, 면회</b>',
 '<b>러시안 소설</b>',
 '<b>극장</b>판 포켓몬스터2: 루기아의 탄생',
 '<b>사랑을 말하다</b>',
 '<b>위대한 비행</b>',
 '<b>몽타주</b>',
 '<b>노리개</b>: 그녀의 눈물',
 '<b>박수건달</b>',
 '<b>죽지않아</b>',
 '<b>연애의 온도</b>',
 '<b>신세계</b>',
 '<b>힘내세요, 병헌씨</b>',
 '<b>이별계약</b>',
 '<b>파파로티</b>',
 '<b>도희야</b>',
 '<b>레바논 감정</b>',
 '<b>국제시장</b>',
 '<b>디셈버</b>',
 '<b>수상한 그녀</b>',
 '<b>만찬</b>',
 '<b>감기</b>',
 '<b>스파이 파파</b>',
 '<b>변호인</b>',
 '<b>톱스타</b>',
 '<b>잉투기</b>',
 '<b>롤러코스터</b>',
 '<b>협녀, 칼의 기억</b>',
 '<b>타투</b>',
 '<b>창수</b>',
 '<b>기타가 웃는다</b>',
 '<b>동창생</b>',
 '<b>명왕성</b>',
 '<b>도둑들</b>',
 '<b>자, 이제 댄스타임</b>',
 '<b>쩨쩨한 로맨스</b>',
 '<b>렛 미 아웃</b>',
 '상감<b>마마</b> 미워요',
 '<b>파수꾼</b>',
 '<b>하울링</b>',
 '<b>감시자들</b>',
 '<b>남자가 사랑할 때</b>',
 '<b>더 테러 라이브</b>',
 '<b>설국열차</b>',
 '<b>공정사회</b>',
 '<b>평양성</b>',
 '<b>악마를 보았다</b>',
 '<b>무적자</b>',
 '<b>두 번의 결혼식과 한 번의 장례식</b>',
 '<b>내 깡패 같은 애인</b>',
 '<b>이끼</b>',
 '<b>곤지암</b>',
 '<b>극비수사</b>',
 '<b>7광구</b>',
 '방콕 킥복서',
 '<b>간기남</b>',
 '<b>홈 스위트 홈</b>',
 '<b>그대를 사랑합니다</b>',
 '<b>달빛 길어올리기</b>',
 '<b>황해</b>',
 '반도',
 '<b>차이나타운</b>',
 '<b>무뢰한</b>',
 '<b>간신</b>',
 '<b>손님</b>',
 '<b>제 7기사단</b>',
 '<b>악의 연대기</b>',
 '<b>명량</b>',
 '<b>미쓰 와이프</b>',
 '<b>경성학교: 사라진 소녀들</b>',
 '<b>내부자들</b>',
 '<b>상의원</b>',
 '<b>나의 사랑 나의 신부</b>',
 '<b>약장수</b>',
 '<b>수색역</b>',
 '<b>검사외전</b>',
 '<b>한강블루스</b>',
 '<b>자백</b>',
 '<b>특종: 량첸살인기</b>',
 '<b>도리화가</b>',
 '<b>삼례</b>',
 '<b>순정</b>',
 '<b>치외법권</b>',
 '<b>널 기다리며</b>',
 '<b>사돈의 팔촌</b>',
 '<b>귀향</b>, 끝나지 않은 이야기',
 '<b>위대한 소원</b>',
 '<b>대호</b>',
 '<b>스틸 플라워</b>',
 '<b>동주</b>',
 '<b>덕혜옹주</b>',
 '<b>탐욕의 별</b>',
 '<b>검은 사제들</b>',
 '<b>그놈이다</b>',
 '<b>소통과 거짓말</b>',
 '<b>오빠생각</b>',
 '<b>탐정 홍길동: 사라진 마을</b>',
 '<b>우아한 거짓말</b>',
 '<b>사도</b>',
 '<b>헬머니</b>',
 '<b>성실한 나라의 앨리스</b>',
 '<b>패션왕</b>',
 '<b>다우더</b>',
 '<b>뷰티 인사이드</b>',
 '<b>서울연애</b>',
 '<b>바세코의 아이들</b>',
 '<b>내 심장을 쏴라</b>',
 '<b>인간중독</b>',
 '<b>조류인간</b>',
 '<b>황제를 위하여</b>',
 '<b>4등</b>',
 '<b>들개</b>',
 '<b>개를 훔치는 완벽한 방법</b>',
 '<b>일대일</b>',
 '<b>쎄시봉</b>',
 '<b>베테랑</b>',
 '<b>개: dog eat dog</b>',
 '<b>뷰티풀 차일드</b>',
 '<b>씨, 베토벤</b>',
 '<b>살인의뢰</b>',
 '<b>오늘의 연애</b>',
 '<b>스케치</b>',
 '<b>더 테너 리리코 스핀토</b>',
 '<b>관능의 법칙</b>',
 '<b>우는 남자</b>',
 '<b>경주</b>',
 '<b>화장</b>',
 '<b>열한시</b>',
 '<b>관상</b>',
 '<b>용의자</b>',
 '<b>한공주</b>',
 '<b>셔틀콕</b>',
 '<b>스타: 빛나는 사랑</b>',
 '<b>소녀괴담</b>',
 '<b>곤충왕국 3D</b>',
 '<b>연평해전</b>',
 '<b>순수의 시대</b>',
 '<b>신의 한 수</b>',
 '<b>하이힐</b>',
 '<b>레쓰링</b>',
 '어둠의 <b>표적</b>',
 '<b>끝까지 간다</b>',
 '<b>의궤, 8일간의 축제 3D</b>',
 '<b>역린</b>',
 '<b>위험한 관계</b>',
 '<b>여의도</b>',
 '<b>죽이러 갑니다</b>',
 '<b>퀴즈왕</b>',
 '<b>폐가</b>',
 '<b>레드카펫</b>',
 '<b>김복남 살인사건의 전말</b>',
 '<b>방가? 방가</b>!',
 '<b>헬로우 고스트</b>',
 '<b>사랑한다, 사랑하지 않는다</b>',
 '<b>짐승</b>',
 '<b>티끌모아 로맨스</b>',
 '<b>거인</b>',
 '<b>카트</b>',
 '<b>마담 뺑덕</b>',
 '<b>타짜-신의 손</b>',
 '<b>막걸스</b>',
 '<b>소리굽쇠</b>',
 '<b>스물</b>',
 '<b>태양을 쏴라</b>',
 '<b>암살</b>',
 '<b>강남 1970</b>',
 '<b>현기증</b>',
 '<b>쓰리 썸머 나잇</b>',
 '<b>또 하나의 약속</b>',
 '<b>산다</b>',
 '<b>이불</b>',
 '<b>장수상회</b>',
 '<b>소셜포비아</b>',
 '<b>님아, 그 강을 건너지 마오</b>',
 '<b>나의 독재자</b>',
 '<b>안녕, 투이</b>',
 '레드 블레이드: 최강닌자<b>소녀</b>의 탄생',
 '<b>지옥화</b>',
 '<b>족구왕</b>',
 '<b>한여름의 판타지아</b>',
 '<b>황구</b>',
 '<b>아가씨</b>',
 '<b>방황하는 칼날</b>',
 '<b>히말라야</b>',
 '<b>허삼관</b>',
 '<b>해적: 바다로 간 산적</b>',
 '<b>숫호구</b>',
 '<b>1987</b>']

In [264]:
df[0]

'스왈로 탐험대와 아마존 해적'

In [296]:
m = search_title(df[3])

for n in (range(len(m))):
        if m[n]['director'][:-1] == data[data['title'] == f'{keyword}']['directors'].values:
            break
        
link = m[n]['link']
spl = str(link).split("=")
it = spl[1]

In [297]:
it

'172040'

In [293]:
title1 = m[n]['title']
title1

'<b>물괴</b>'

In [301]:
code_lst

['143399',
 '132996',
 '146459',
 '172040',
 '141221',
 '109867',
 '167787',
 '169649',
 '167647',
 '179712',
 '168054',
 '178654',
 '164102',
 '138601',
 '179303',
 '174329',
 '179446',
 '179185',
 '173833',
 '172010',
 '174305',
 '141206',
 '154449',
 '167720',
 '173469',
 '179840',
 '173413',
 '162423',
 '172194',
 '178803',
 '171911',
 '170405',
 '147029',
 '154271',
 '161115',
 '179430',
 '152632',
 '177442',
 '137343',
 '170456',
 '172145',
 '178761',
 '137962',
 '179713',
 '179250',
 '143373',
 '168669',
 '144266',
 '178632',
 '179708',
 '169015',
 '144958',
 '176711',
 '151280',
 '141973',
 '141158',
 '151117',
 '132939',
 '154273',
 '164269',
 '171238',
 '178875',
 '196367',
 '174262',
 '176746',
 '151886',
 '177357',
 '168738',
 '158620',
 '176747',
 '166585',
 '163744',
 '175318',
 '178426',
 '159864',
 '78525',
 '142683',
 '172996',
 '147018',
 '116509',
 '177497',
 '160009',
 '193618',
 '164126',
 '157172',
 '168018',
 '161693',
 '109906',
 '158191',
 '170396',
 '172137',
 '177975',
 '154982',
 '178403',
 '172798',
 '164155',
 '152621',
 '178816',
 '140213',
 '178818',
 '179187',
 '149027',
 '168679',
 '168991',
 '178429',
 '171541',
 '154667',
 '35067',
 '158112',
 '154112',
 '149417',
 '142250',
 '48971',
 '164139',
 '162265',
 '168023',
 '180361',
 '170267',
 '144323',
 '168059',
 '155263',
 '167481',
 '181025',
 '163787',
 '154669',
 '173667',
 '175481',
 '189257',
 '182713',
 '184912',
 '175149',
 '177757',
 '155715',
 '183481',
 '183513',
 '147045',
 '183275',
 '174268',
 '179461',
 '183453',
 '179667',
 '181013',
 '187351',
 '158180',
 '162295',
 '155716',
 '184995',
 '162294',
 '180374',
 '149512',
 '155041',
 '182618',
 '182619',
 '152387',
 '137946',
 '186663',
 '180429',
 '155680',
 '154219',
 '185045',
 '187597',
 '181912',
 '162932',
 '180002',
 '165458',
 '185155',
 '187365',
 '200052',
 '176622',
 '164116',
 '142633',
 '182621',
 '134891',
 '167648',
 '161242',
 '158536',
 '173653',
 '149479',
 '179683',
 '181017',
 '180687',
 '178483',
 '171921',
 '181095',
 '165809',
 '160953',
 '155411',
 '182012',
 '147036',
 '174269',
 '193128',
 '152648',
 '171466',
 '108052',
 '179235',
 '164992',
 '178871',
 '163716',
 '178849',
 '167638',
 '165020',
 '148647',
 '190727',
 '143388',
 '174832',
 '172197',
 '137327',
 '145264',
 '158178',
 '154255',
 '178434',
 '183855',
 '134895',
 '127391',
 '171336',
 '186664',
 '183479',
 '167062',
 '179392',
 '15489',
 '140649',
 '176033',
 '184178',
 '183520',
 '168049',
 '154508',
 '179414',
 '174292',
 '179689',
 '168019',
 '171490',
 '183741',
 '156195',
 '172031',
 '175255',
 '163900',
 '171414',
 '162014',
 '142251',
 '172344',
 '163824',
 '166482',
 '171441',
 '169647',
 '116146',
 '162854',
 '168017',
 '162406',
 '163664',
 '173004',
 '144183',
 '174798',
 '143416',
 '154285',
 '163682',
 '174804',
 '158890',
 '169532',
 '162395',
 '153675',
 '171888',
 '68291',
 '175325',
 '118184',
 '159805',
 '171408',
 '164796',
 '163850',
 '154292',
 '145747',
 '154251',
 '171746',
 '171443',
 '162405',
 '172525',
 '168479',
 '108360',
 '165768',
 '45425',
 '174811',
 '152680',
 '159839',
 '175365',
 '175617',
 '25992',
 '172420',
 '144693',
 '163893',
 '150097',
 '137702',
 '170289',
 '171877',
 '170637',
 '158885',
 '168110',
 '159037',
 '171744',
 '156148',
 '143371',
 '166415',
 '159834',
 '115511',
 '152656',
 '168518',
 '167482',
 '158645',
 '167408',
 '143463',
 '170953',
 '170664',
 '159105',
 '169546',
 '103304',
 '128912',
 '169517',
 '157695',
 '109960',
 '71036',
 '173692',
 '150687',
 '168418',
 '165026',
 '168523',
 '168517',
 '164337',
 '189361',
 '169899',
 '129673',
 '171768',
 '154598',
 '149236',
 '118736',
 '126052',
 '129256',
 '72089',
 '172562',
 '171764',
 '150658',
 '148995',
 '151744',
 '149501',
 '170286',
 '170457',
 '154270',
 '144942',
 '169262',
 '158631',
 '154550',
 '173784',
 '175614',
 '177508',
 '169688',
 '149702',
 '114057',
 '177379',
 '172174',
 '172472',
 '104094',
 '136990',
 '173145',
 '159670',
 '168735',
 '177507',
 '164113',
 '163660',
 '170806',
 '160375',
 '33152',
 '152661',
 '171446',
 '186147',
 '167602',
 '163851',
 '175317',
 '47933',
 '167388',
 '177335',
 '170970',
 '172967',
 '177222',
 '170824',
 '172425',
 '165106',
 '127335',
 '177378',
 '171576',
 '169643',
 '177220',
 '160721',
 '177227',
 '171727',
 '177225',
 '177381',
 '174257',
 '172768',
 '174301',
 '158621',
 '178215',
 '170888',
 '165479',
 '177368',
 '159883',
 '162908',
 '172592',
 '171727',
 '172009',
 '172034',
 '163679',
 '171754',
 '164684',
 '176513',
 '160487',
 '172600',
 '143776',
 '53547',
 '171407',
 '167763',
 '172777',
 '121762',
 '118343',
 '166463',
 '156532',
 '172006',
 '66676',
 '171822',
 '169561',
 '170139',
 '154433',
 '151740',
 '158647',
 '171810',
 '159731',
 '164747',
 '140285',
 '177250',
 '159092',
 '160699',
 '172019',
 '172118',
 '171499',
 '157340',
 '62907',
 '175727',
 '173019',
 '176896',
 '111186',
 '154222',
 '176892',
 '154625',
 '175591',
 '162002',
 '178250',
 '86605',
 '152475',
 '172113',
 '144330',
 '168030',
 '166476',
 '159627',
 '152682',
 '176743',
 '176524',
 '177377',
 '189241',
 '97631',
 '181701',
 '167651',
 '140696',
 '183494',
 '172187',
 '194027',
 '187541',
 '186616',
 '189959',
 '164189',
 '193219',
 '186349',
 '186033',
 '179973',
 '184918',
 '155218',
 '189368',
 '186035',
 '216494',
 '187411',
 '169217',
 '182777',
 '185286',
 '181144',
 '190574',
 '189244',
 '183783',
 '189292',
 '168043',
 '188153',
 '182001',
 '151151',
 '151674',
 '181014',
 '154291',
 '178857',
 '184919',
 '187051',
 '189291',
 '183803',
 '186610',
 '155779',
 '150027',
 '179482',
 '182020',
 '154983',
 '186659',
 '192364',
 '173810',
 '73665',
 '174530',
 '181104',
 '183508',
 '183507',
 '173840',
 '116135',
 '183506',
 '193850',
 '174261',
 '179397',
 '186660',
 '173812',
 '159093',
 '176040',
 '168405',
 '142201',
 '119814',
 '181717',
 '173020',
 '171452',
 '140652',
 '188360',
 '151738',
 '188361',
 '173247',
 '144990',
 '137917',
 '164153',
 '193839',
 '179666',
 '184962',
 '181570',
 '181074',
 '184204',
 '148442',
 '174297',
 '181069',
 '174265',
 '180370',
 '179318',
 '119555',
 '158622',
 '152691',
 '189260',
 '190598',
 '12906',
 '191031',
 '190643',
 '189139',
 '173575',
 '185933',
 '187583',
 '167374',
 '187508',
 '159366',
 '182387',
 '52720',
 '167054',
 '154000',
 '174903',
 '178451',
 '167605',
 '167100',
 '188339',
 '181039',
 '165748',
 '159877',
 '189293',
 '158652',
 '176738',
 '170311',
 '186642',
 '162415',
 '183457',
 '181021',
 '193209',
 '189624',
 '189621',
 '159879',
 '187161',
 '161500',
 '188765',
 '164145',
 '132617',
 '180992',
 '182736',
 '189885',
 '172152',
 '174730',
 '191086',
 '171467',
 '189968',
 '182788',
 '187635',
 '181698',
 '189063',
 '181103',
 '181037',
 '185131',
 '189960',
 '182756',
 '189023',
 '158558',
 '170859',
 '159760',
 '168029',
 '184958',
 '148863',
 '180162',
 '152168',
 '189961',
 '155256',
 '184859',
 '183502',
 '183657',
 '187595',
 '169522',
 '187874',
 '167637',
 '172758',
 '178148',
 '189619',
 '130968',
 '182579',
 '169347',
 '186704',
 '186705',
 '190373',
 '184308',
 '162203',
 '160399',
 '181276',
 '167445',
 '173123',
 '191237',
 '169614',
 '179697',
 '98834',
 '172005',
 '170860',
 '170310',
 '152659',
 '155116',
 '173526',
 '183836',
 '72033',
 '179181',
 '164293',
 '184999',
 '172200',
 '161876',
 '171472',
 '191677',
 '167675',
 '145375',
 '183600',
 '179125',
 '171736',
 '188872',
 '152331',
 '137865',
 '154429',
 '184959',
 '184957',
 '166543',
 '167335',
 '184965',
 '159887',
 '174083',
 '85331',
 '159807',
 '181003',
 '179643',
 '191548',
 '154672',
 '185292',
 '187507',
 '110387',
 '187645',
 '185925',
 '175045',
 '131553',
 '147836',
 '86429',
 '179721',
 '186672',
 '189463',
 '190377',
 '172003',
 '181411',
 '137948',
 '186219',
 '177400',
 '147872',
 '184240',
 '186235',
 '180462',
 '148304',
 '213633',
 '186662',
 '186036',
 '185638',
 '184906',
 '153934',
 '143435',
 '180349',
 '167560',
 '162296',
 '144787',
 '186044',
 '184366',
 '182206',
 '146433',
 '164979',
 '149290',
 '173525',
 '167615',
 '189027',
 '175498',
 '177352',
 '142086',
 '179127',
 '126497',
 '188368',
 '180220',
 '156466',
 '188379',
 '188370',
 '170890',
 '173804',
 '188377',
 '74407',
 '185485',
 '184320',
 '183427',
 '185149',
 '183828',
 '183480',
 '167671',
 '163818',
 '183514',
 '179671',
 '162196',
 '140656',
 '186661',
 '164125',
 '140110',
 '182406',
 '163826',
 '161868',
 '167635',
 '186348',
 '179020',
 '168298',
 '168038',
 '189274',
 '208980',
 '148000',
 '186648',
 '73144',
 '164172',
 '167097',
 '168745',
 '102826',
 '159866',
 '183478',
 '127322',
 '190590',
 '190306',
 '163786',
 '152183',
 '154984',
 '181566',
 '171474',
 '190979',
 '149289',
 '189288',
 '184975',
 '186677',
 '172764',
 '189256',
 '186707',
 '183110',
 '181711',
 '164956',
 '113170',
 '59139',
 '183113',
 '181414',
 '11004',
 '182642',
 '177511',
 '130806',
 '192121',
 '179420',
 '177543',
 '27650',
 '187310',
 '167542',
 '177371',
 '72313',
 '176912',
 '175586',
 '151550',
 '181078',
 '183870',
 '158623',
 '175878',
 '159684',
 '187390',
 '186050',
 '152679',
 '190644',
 '180397',
 '173754',
 '181565',
 '179126',
 '179841',
 '176354',
 '158884',
 '168749',
 '107438',
 '171465',
 '159893',
 '192619',
 '178097',
 '167443',
 '180381',
 '119460',
 '188350',
 '189100',
 '183482',
 '137876',
 '172070',
 '190608',
 '170663',
 '180351',
 '185268',
 '186615',
 '92125',
 '162153',
 '189900',
 '186238',
 '74372',
 '171725',
 '85578',
 '159311',
 '172819',
 '146517',
 '43233',
 '129282',
 '185282',
 '170290',
 '38578',
 '189205',
 '138599',
 '184759',
 '172605',
 '187349',
 '189202',
 '143472',
 '194295',
 '183804',
 '186236',
 '168047',
 '147040',
 '152156',
 '162867',
 '174296',
 '153687',
 '179416',
 '181959',
 '164192',
 '185479',
 '167699',
 '130939',
 '167597',
 '114262',
 '189123',
 '171884',
 '163842',
 '155547',
 '136889',
 '144927',
 '144081',
 '152257',
 '127346',
 '158873',
 '158888',
 '158790',
 '126504',
 '147896',
 '136827',
 '140792',
 '19903',
 '144840',
 '159580',
 '127383',
 '156337',
 '161294',
 '161308',
 '102638',
 '154214',
 '28224',
 '148946',
 '158485',
 '141337',
 '162962',
 '129230',
 '161323',
 '92413',
 '142324',
 '160218',
 '143372',
 '158634',
 '143188',
 '160720',
 '117787',
 '158775',
 '155650',
 '151249',
 '155228',
 '144215',
 '144352',
 '132627',
 '207320',
 '134892',
 '144114',
 '146200',
 '159286',
 '152491',
 '161365',
 '159110',
 '162148',
 '144988',
 '154053',
 '163051',
 '168507',
 '161374',
 '125447',
 '134987',
 '118966',
 '144202',
 '119546',
 '164397',
 '156083',
 '143499',
 '155020',
 '143428',
 '136899',
 '159827',
 '153628',
 '163014',
 '139701',
 '126011',
 '151885',
 '125418',
 '140730',
 '163093',
 '181569',
 '143473',
 '141490',
 '143099',
 '163095',
 '204624',
 '153342',
 '160464',
 '123630',
 '134887',
 '162260',
 '159595',
 '142632',
 '195246',
 '159402',
 '151673',
 '149731',
 '140695',
 '127389',
 '163086',
 '138593',
 '129055',
 '146480',
 '162933',
 '164298',
 '140776',
 ...]

In [304]:
import csv
with open('movie_buzz_codelist.csv', 'w', newline='') as f: 
    writer = csv.writer(f) 
    writer.writerow(code_lst)

In [54]:
code_lst = pd.read_csv('movie_buzz_codelist.csv')
code_lst=list(map(float,code_lst))

ValueError: could not convert string to float: 'nan.1'

In [52]:
code

AttributeError: 'list' object has no attribute 'dtype'

가져온 고유코드로 리뷰 가져오기

In [12]:
from urllib.request import urlopen 
from bs4 import BeautifulSoup
import requests
import time

In [13]:
date_list = []
title_list2 = []


for i in range(len(code_lst)):
    url = f'https://movie.naver.com/movie/bi/mi/review.naver?code={code_lst[i]}'
    html =urlopen(url)
    soup = BeautifulSoup(html,'html.parser')
    w = str(soup.select('div>div>div>div>div>div>div>span>em'))
    try:
        import re
        reg = re.compile('\d')
        per_result = reg.findall(w)
        y = ''.join(per_result)
        z = int(y)//10 +2


        date_2 = []
        for page in range(1,z):
            url2 = f'https://movie.naver.com/movie/bi/mi/review.naver?code={code_lst[i]}&page={page}'
            html2 =urlopen(url2)

            soup = BeautifulSoup(html2,'html.parser')

            date_num = soup.select('li>span>em')

            date_2.extend(date_num)
            time.sleep(2) 
        y = str(date_2).split(',')
        reg = re.compile('[^a-zA-Z가-힣\>]\d*\.\d*\.\d*')
        e = ''.join(y)
        per_result = reg.findall(e)
        datetime_result = pd.to_datetime(per_result)
        date_list.append(datetime_result)

        tit = soup.select('title')
        a = str(tit).split(":")
        b =a[0].replace('[','').replace('<','').replace('title','').replace('>','').replace(' ','')
        title_list2.append(b)
    
    except:
        date_list.append(0)
        url = f'https://movie.naver.com/movie/bi/mi/review.naver?code={code_lst[i]}'
        html =urlopen(url)
        soup = BeautifulSoup(html,'html.parser')
        tit = soup.select('title')
        a = str(tit).split(":")
        b =a[0].replace('[','').replace('<','').replace('title','').replace('>','').replace(' ','')
        title_list2.append(b)
print(len(date_list))
print(len(title_list2))

575
575

In [14]:
len(date_list)#4270

575

In [19]:
import csv
with open('movie_buzz_한국만title.csv', 'w', newline='') as f: 
    writer = csv.writer(f) 
    writer.writerow(title_list2)

밑에코드는 신경 안쓰셔도 됩니다

In [21]:
import pandas as pd
one_title = pd.read_csv('movie_buzz_한국만title.csv', encoding='UTF-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 0: invalid start byte

In [17]:
one = one_date.transpose()
one.reset_index(inplace= True)

In [18]:
one

                                                 index
0    DatetimeIndex(['2018-09-12', '2018-08-08', '20...
1    DatetimeIndex(['2017-02-22', '2016-06-23', '20...
2    DatetimeIndex(['2018-06-30', '2018-06-19', '20...
3    DatetimeIndex(['2018-10-27', '2018-03-12', '20...
4    DatetimeIndex(['2018-04-20', '2019-01-16', '20...
..                                                 ...
570  DatetimeIndex(['2015-12-16', '2015-12-18', '20...
571  DatetimeIndex(['2015-01-14', '2015-01-13', '20...
572  DatetimeIndex(['2014-07-24', '2014-07-20', '20...
573  DatetimeIndex(['2012-04-22', '2014-07-31', '20...
574  DatetimeIndex(['2017-11-10', '2017-12-21', '20...

[575 rows x 1 columns]

In [22]:
date = data['개봉일']

In [25]:
data['개봉일'] = pd.to_datetime(data['개봉일'])

In [23]:
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

In [105]:
date = []
for day in range(len(one)):
    end_date = data['개봉일'][day] - relativedelta(days=1) 
    end_date = end_date.strftime('%Y%m%d') 
    
    a = date_list[day] < end_date
    a = list(a)
    num = a.count(True)
    date.append(num)

In [108]:
date_df = pd.DataFrame({"movie_buzz_naver":date})

In [109]:
date_df

     movie_buzz_naver
0                  22
1                  19
2                  30
3                   6
4                   5
..                ...
570               219
571               124
572               379
573                25
574                61

[575 rows x 1 columns]

In [110]:
date_df.to_csv('movie_buzz_naver.csv', index=False, )

In [7]:
two_date = pd.read_csv('movie_buzz2_3000~4500_datelist.csv')
three_date = pd.read_csv('movie_buzz2_4500_5199_datelist.csv')
four_date = pd.read_csv('movie_buzz2_5200~_datelist.csv')

In [8]:
two = two_date.transpose()
two.reset_index(inplace= True)
three = three_date.transpose()
three.reset_index(inplace= True)
four = four_date.transpose()
four.reset_index(inplace= True)

In [18]:
#one_title = pd.read_csv('movie_buzz2_3000_title.csv')
#two_title = pd.read_csv('movie_buzz2_3000~4500_datelist.csv')
three_title = pd.read_csv('movie_buzz2_4500_5199_titlelist.csv',encoding='UTF=8')
four_title = pd.read_csv('movie_buzz2_5200~_titlelist.csv',encoding='UTF=8')

In [19]:
#one_title = one_title.transpose()
#one_title.reset_index(inplace= True)
#two_title = two_title.transpose()
#two_title.reset_index(inplace= True)
three_title = three_title.transpose()
three_title.reset_index(inplace= True)
four_title = four_title.transpose()
four_title.reset_index(inplace= True)

In [20]:
movie_buzz_df_3_4 = pd.concat([three,four], axis=0)

In [23]:
movie_buzz_df_3_4

                                                  index
0     DatetimeIndex(['2012-04-11', '2012-07-15', '20...
1     DatetimeIndex(['2012-01-29', '2012-01-11', '20...
2     DatetimeIndex([], dtype='datetime64[ns]', freq...
3     DatetimeIndex(['2012-05-25', '2012-05-18', '20...
4     DatetimeIndex(['2011-12-16', '2011-12-25', '20...
...                                                 ...
1153  DatetimeIndex(['2013-08-18', '2014-09-18', '20...
1154  DatetimeIndex(['2014-12-21', '2015-01-11', '20...
1155  DatetimeIndex(['2014-12-09', '2015-02-13'], dt...
1156  DatetimeIndex(['2014-12-09', '2015-01-16', '20...
1157  DatetimeIndex(['2014-08-30', '2014-08-21', '20...

[1851 rows x 1 columns]

In [32]:
movie_buzz_df_title_3_4 = pd.concat([three,three_title], axis=1)

In [28]:
df = pd.DataFrame({"date":three, "title":three_title})
df

SyntaxError: invalid syntax (<ipython-input-28-0a9fdc819ef2>, line 1)

In [113]:
#_df.to_csv('t_df.csv', index=False, )